### ISSUE TITLE
4th Class Generation broken

### ISSUE THREAD

**Issue by Dace617** [tiquionophist/hhs-scheduler#15]
When generating 4 classes the first 3 classes generate full schedules however, the fourth class only applies two subjects to the entire schedule and leaves the rest of the subjects as "Empty" 

If I add a 5th class it generates fine but the 4th Class is still only 2 subjects with the rest empty.

I've tried various classroom selection and fill orders but can't seem to work around this

Screenshots:
Class 4: 
![image](https://user-images.githubusercontent.com/38520983/173481082-c2426b5d-ef42-4ab0-9b7d-e54bedc3fb1f.png)
Class 2 from the same generation: 
![image](https://user-images.githubusercontent.com/38520983/173481124-063a56cf-44ba-40b4-9b66-0ac533ece8df.png)

**Comment by tiquionophist** [comment]
Thanks for the report. I've seen something similar after importing from a save and then adding classes to it - is that's what happened in your case? If so, a workaround is to add the desired number of classes in-game and then re-import it. I'll try to find a fix soon, but let me know if that works in the meantime.

**Comment by Dace617** [comment]
I was sure I had added the extra class before importing my save, which I usually do. But having tried re-importing my save again just now, with the 4th class already added it seems to be generating the 4th class just fine. 

Sorry about that, If I can replicate it again and have a better idea of what I did to break it I'll let you know.

**Comment by tiquionophist** [comment]
I think I found the issue: when importing a save, if different classes have a different number of subjects/week the UI didn't display that (i.e. "per-class scheduling" was still unchecked). It was still silently trying to follow that pre-existing configuration, but didn't prompt the user about this in any way.

In 1.3.2 this should be fixed by (a) correctly setting the per-class scheduling checkbox after importing and (b) showing a dialog if subject frequency is different across classes so this is hopefully clearer.

Feel free to re-open if you still see this issue or have ideas for how else to handle this case.
