### ISSUE TITLE
2 UI issues

### ISSUE THREAD

**Issue by TheWABBIT1** [tiquionophist/hhs-scheduler#7]
I am using the v1.1.3 standalone version. And I have come across two UI issues.

Issue #1: when ever I click on the settings button and the settings windows opens up. the window is opened to were the top and bottom of the window is completely off the desktop screen. attempting to move the window with either of the two frame sides. Causes the window to automatically resize until the bottom of the window is visible on desktop. And resizing of the window goes without any problems.
![UI_Issue_1](https://user-images.githubusercontent.com/11741009/141951836-02f78b29-2a32-4957-b197-57ef88e18603.png)

Issue #2: In the Scheduler Settings, clicking on the Fill order dropbox causes the dropbox selection items to be displayed to the far left of the Scheduler Settings window. And you unable to select option that you want.
![UI_Issue_2](https://user-images.githubusercontent.com/11741009/141951914-322c23de-6a2a-4072-a569-d902fc026ac0.png)

**Comment by tiquionophist** [comment]
Thanks for the report! I've adjusted the dialog size to mitigate the first issue - it's something my UI framework doesn't handle well, unfortunately, but I hope this will work for you. The second issue is fixed in the latest release of that UI framework - must have slipped in since I last tested it.
