### ISSUE TITLE
Add back-to-back class constraint

### ISSUE THREAD

**Issue by tiquionophist** [tiquionophist/hhs-scheduler#8]
Add a feature to prevent the same class being scheduled back-to-back.

**Comment by TheWABBIT1** [comment]
I figured that I would place this here, instead of creating a new issue/request.

As much as I would like to constrain the Back-to-Back of the same class subjects. I think it would also be much better not to have the same class subject more than once in a single day.

What do I mean by this? Well, if you have 4 or more class subjects being taught. Then there is no reason for any class subject to be repeated in any single day for any of the classes.
